name: AnubisCore
version: '${version}'
softdepend:
  - PlaceholderAPI
  - FactionsKore
  - ManticHoes
  - ManticSwords
  - ManticRods
depend:
  - CombatTagPlus
  - Factions
main: com.candyrealms.candycore.AnubisCore
